name: 'Chromatic Deployment'

on: push

jobs:
  test:
    # Operating System
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npx chromatic --project-token=5e55da8ec418
      - uses: chromaui/action@v1
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
          # projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}